Repository L-W-payments/asaas-payment, pull requests merged in 2024-06, with the labels that each got.

#143 Corrigindo erros do merge
  grails-app/controllers/com/miniasaaslw/controller/customer/CustomerController.groovy
  grails-app/controllers/com/miniasaaslw/controller/payer/PayerController.groovy
Labels: bugFix

#132 Atualizando README do projeto
  README.md
Labels: Aguardando Outro PR

#209 Resolvendo erro nas mensagens de erro do recibo
  grails-app/i18n/messages_pt_BR.properties
  grails-app/services/com/miniasaaslw/service/paymentreceipt/PaymentReceiptService.groovy
Labels: Corrigindo erro

#214 [Spring security 4] - Adicionando contexto de salvar usuário
  grails-app/controllers/com/miniasaaslw/controller/user/UserController.groovy
  grails-app/i18n/messages_pt_BR.properties
  grails-app/init/com/miniasaaslw/BootStrap.groovy
  grails-app/services/com/miniasaaslw/service/user/UserService.groovy
  src/main/groovy/com/miniasaaslw/adapters/user/UserAdapter.groovy
  src/main/groovy/com/miniasaaslw/utils/PasswordUtils.groovy
Labels: Aguardando outro PR

#230 [User 3] Tela de visualização do Usuário
  grails-app/controllers/com/miniasaaslw/controller/user/UserController.groovy
  grails-app/i18n/messages_pt_BR.properties
  grails-app/services/com/miniasaaslw/service/user/UserService.groovy
  grails-app/views/user/show.gsp
  grails-app/views/user/templates/_userForm.gsp
Labels: Aguardando outro PR

#225 [User 2] Criando listagem de usuários
  grails-app/assets/javascripts/UserListController.js
  grails-app/controllers/com/miniasaaslw/controller/user/UserController.groovy
  grails-app/views/templates/_sidebar.gsp
  grails-app/views/user/list.gsp
  grails-app/views/user/templates/_table.gsp
  grails-app/views/user/templates/_tableContent.gsp
  src/main/groovy/com/miniasaaslw/repository/user/UserRepository.groovy
Labels: Aguardando outro PR

#255 [Bugfix] Refatoração da validação de data de vencimento da cobrança
  build.gradle
  grails-app/services/com/miniasaaslw/service/payment/PaymentService.groovy
  src/main/groovy/com/miniasaaslw/utils/DateUtils.groovy
Labels: Corrigindo erro

#264 Melhorando tela de login
  grails-app/assets/javascripts/LoginController.js
  grails-app/assets/stylesheets/login.scss
  grails-app/views/login/auth.gsp
Labels: Aguardando outro PR

#267 [Customer/User] Alterar e-mail do usuário quando o do customer for alterado
  grails-app/controllers/com/miniasaaslw/controller/customer/CustomerController.groovy
  grails-app/i18n/messages_pt_BR.properties
  grails-app/services/com/miniasaaslw/service/customer/CustomerService.groovy
  grails-app/services/com/miniasaaslw/service/user/UserService.groovy
  src/main/groovy/com/miniasaaslw/adapters/user/UserAdapter.groovy
  src/main/groovy/com/miniasaaslw/utils/EmailUtils.groovy
Labels: Aguardando outro PR

#266 [User] Proibir usuário ADMIN de deletar sua conta e ocultar da lista de usuários.
  grails-app/controllers/com/miniasaaslw/controller/user/UserController.groovy
  grails-app/i18n/messages_pt_BR.properties
  grails-app/services/com/miniasaaslw/service/user/UserService.groovy
  src/main/groovy/com/miniasaaslw/repository/user/UserRepository.groovy
Labels: Aguardando outro PR

#275 [Bugfix] Corrigindo exceção lançada errada
  grails-app/services/com/miniasaaslw/service/user/UserService.groovy
Labels: Corrigindo erro
